version: '3.8'

services:
  postgres:
    image: postgres:16.0-alpine
    container_name: anonymous_chat_postgres_container
    environment:
      POSTGRES_DB: anonymous_chat_development
      POSTGRES_USER: anonymous_chat
      POSTGRES_PASSWORD: anonymous_chat
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - anonymous_chat_network

  redis:
    image: redis:7.0-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - anonymous_chat_network

volumes:
  postgres_data:
  redis_data:

networks:
  anonymous_chat_network:
