default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: anonymous_chat_development
  username: anonymous_chat
  password: anonymous_chat
  host: localhost
  port: 5432

test:
  <<: *default
  database: anonymous_chat_test

production:
  <<: *default
  database: anonymous_chat_production
  username: anonymous_chat
  password: <%= ENV["ANONYMOUS_CHAT_DATABASE_PASSWORD"] %>
